name: Cron job to trigger API

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-cron-task:
    runs-on: ubuntu-latest
    steps:
      - name: Log the current time (for debugging)
        run: date
        
      - name: Trigger dailyComboCards task
        run: |
          echo "Triggering dailyComboCards API..."
          curl -X GET https://panda-tap-dashboard-backend.vercel.app/random-card-status-update
          echo "API trigger completed successfully."
