name: Cron job to trigger API

on:
  schedule:
    - cron: "0 19 * * *"  # 7:00 PM UTC = 12:00 AM PKT (Karachi time)
  workflow_dispatch:

jobs:
  run-cron-task:
    runs-on: ubuntu-latest
    steps:
      - name: Log the current time (for debugging)
        run: date

      - name: Trigger Vercel API
        run: |
          curl -X GET https://panda-tap-dashboard-backend.vercel.app/random-card-status-update
